version: '3.9'
services:
  edufund-svc:
    container_name: edufund_svc
    environment:
      - APP_VERSION="v1.0.0"
      - APP_ENV=local go run -tags dynamic main.go
      - APP_KEY=pretest-edufund
      - APP_NAME=Pretest Edufund
      - APP_HOST=localhost
      - APP_PORT=9091
      - SERVER_HOST_NAME="smtp.gmail.com"
      - SERVER_MAIL_ADDRESS="infodcc.21@gmail.com"
      - JWT_SECRET_KEY="---RAHASIABRO!!!!"
      - DB_ENGINE
      - DB_SSL_MODE
      - DB_HOST
      - DB_NAME
      - DB_PORT
      - DB_PWD
      - DB_USER
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9091:9091
    volumes:
      - .:/go/src/interview/edufund
    command: go run main.go -b 0.0.0.0
    restart: on-failure
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
# Networks to be created to facilitate communication between containers